// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yipxlolcqzqvhykyagvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpcHhsb2xjcXpxdmh5a3lhZ3ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1Njc2ODIsImV4cCI6MjA1ODE0MzY4Mn0.oi_yG3cnLXhXT1a-te2djcDUvTtPVYn6oWQuFWBZQcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);